### ISSUE TITLE
Update Info Card to add my YouTube Link

### ISSUE THREAD

**Issue by Malik-Girondin** [Malik-Girondin/info-card#1]
My info card currently has my LinkedIn, not my YouTube channel. I will need to add the link to the card for future visitors

- [] First, grab my YouTube link: https://www.youtube.com/@malikgirondin/videos
- [] Update the HTML page via Git CLI
- [] Push changes to this repo

**Comment by Shoyebaktar-shirol** [comment]
@Malik-Girondin Hello Please assign me this issue .
